#!/usr/bin/env python
#
# psns: ps for Linux namespaces
#
#

import os
import re
import sys
import commands

def get_ns_pids(debug=False):
    result = []
    for dir, subdirs, files in os.walk('/proc'):
        for dname in subdirs:
          m = re.match(r'\d+', dname)
          if m:
              pid = m.group(0)
              ns = commands.getstatusoutput('ip netns identify %s' % pid)
              if ns[1]:
                m = re.match(r'^Cannot open', ns[1])
                if not m:
                    cmd = commands.getstatusoutput('ps -o args= %s' % pid)
                    result.append((pid, ns[1], cmd[1]))
                    if debug == True:
                        print '%s %s' % (pid, ns[1])
        return result


def main():
    if os.geteuid() != 0:
        exit("Must be root.")

    debug = False
    result = get_ns_pids(debug)
    for tup in result:
        print '%s %s %s' % (tup[0], tup[1], tup[2])


if __name__ == '__main__':
    main()





